name: Basic Runner Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    
    - name: Run some basic commands
      run: |
        ls
        ipconfig /all
        nslookup google.com
