name: Generate OpenSSH Configuration File

on:

  workflow_dispatch:
    inputs:
      ssh_user:
        description: 'SSH Username used for connecting to devices.'
        required: true
      env_choice:
        type: choice
        description: Prod or Dev environment
        required: true
        options:
          - prod
          - dev
      

jobs:
  run_script:
    runs-on: self-hosted
    environment: ${{ inputs.env_choice }}
    steps:
      
      
      - name: 'Cleanup build folder and clone clean repo'
        run: |
          pwd
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./
      
      # Notice that this 'uses' line is part of the 'Cleanup' step above.
      - uses: actions/checkout@v4
        with:
          ref: 'main'
    
      - name: Build Python Environment in Docker Container
        run: |
          docker build -t python:network-automation .

      - name: Execute Script
        run: |
          cd ${{ github.workspace }}
          docker run --rm --name network-automation \
          -e NB_API_TOKEN="$NB_API_TOKEN" \
          -v "$PWD":${{ github.workspace }} \
          -w ${{ github.workspace }} \
          --user $(id -u):$(id -g) \
          python:network-automation \
          python -u ${{ github.workspace }}/src/openssh_config.py \
          -url ${{ vars.NB_URL }} \
          -ssh_user ${{ inputs.ssh_user }}
        env:
          NB_API_TOKEN: ${{ secrets.NB_API_TOKEN }}
      
      - name: Archive Artifact - Config File
        uses: actions/upload-artifact@v4
        with:
          name: OpenSSH Configuration File
          path: |
            ${{ github.workspace }}/artifacts/config
            ${{ github.workspace }}/artifacts/openssh_conf_instructions.txt